name: "provider"
description: "provider"
inputs:
  make:
    description: "make"
    required: true
  command:
    description: "command"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.make }}
    - ${{ inputs.command }}
