name: "provider"
description: "provider"
inputs:
  command:
    description: "command"
    required: true
  arg:
    description: "arg"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.arg }}
